-- CreateTable
CREATE TABLE "Weather" (
    "id" SERIAL NOT NULL,
    "lon" DOUBLE PRECISION NOT NULL,
    "lat" DOUBLE PRECISION NOT NULL,
    "weatherId" INTEGER NOT NULL,
    "main" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "icon" TEXT NOT NULL,
    "base" TEXT NOT NULL,
    "temp" DOUBLE PRECISION NOT NULL,
    "feels_like" DOUBLE PRECISION NOT NULL,
    "temp_min" DOUBLE PRECISION NOT NULL,
    "temp_max" DOUBLE PRECISION NOT NULL,
    "pressure" INTEGER NOT NULL,
    "humidity" INTEGER NOT NULL,
    "sea_level" INTEGER NOT NULL,
    "grnd_level" INTEGER NOT NULL,
    "visibility" INTEGER NOT NULL,
    "wind_speed" DOUBLE PRECISION NOT NULL,
    "wind_deg" INTEGER NOT NULL,
    "wind_gust" DOUBLE PRECISION NOT NULL,
    "rain_1h" DOUBLE PRECISION NOT NULL,
    "clouds_all" INTEGER NOT NULL,
    "dt" INTEGER NOT NULL,
    "sys_type" INTEGER NOT NULL,
    "sys_id" INTEGER NOT NULL,
    "country" TEXT NOT NULL,
    "sunrise" INTEGER NOT NULL,
    "sunset" INTEGER NOT NULL,
    "timezone" INTEGER NOT NULL,
    "city_id" INTEGER NOT NULL,
    "city_name" TEXT NOT NULL,
    "cod" INTEGER NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Weather_pkey" PRIMARY KEY ("id")
);
